### ISSUE TITLE
Changing default color of quiz buttons

### ISSUE THREAD

**Issue by hitestji** [markusbegerow/Wp-Adv-Quiz#1]
All the buttons in the quiz have the same default color, can we set any color according to our own. If yes then how?

**Comment by markusbegerow** [comment]
Hey @hitestji,

you can change the default color of buttons per css modifications.
Otherwise i could implement a color picker in the admin panel to change the color.

**Comment by hitestji** [comment]
I haven't found a plugin like wp pro quiz yet. Although we used a lot of paid plugins as well, there was none like it.

But I expect only one change in this plugin.

The quiz interface is very old, only 1 color has been used for a long time.

That's why we wanted to know about it from you.

You told that we can change the color of buttons etc by 'css modifications'.

Can you make changes to this plugin so that it automatically uses the theme's color and buttons (button text size, button size, etc.)?

Well we used LearnDash, so we came to know that wp pro quiz is being used in the background to conduct quiz in LearnDash. (There was a feature to change the color.)

We would love to donate if you help us modify the color and button size.

Thank you for giving your valuable time.

**Comment by markusbegerow** [comment]
Thank you @hitestji  for your input.
Before I will start with your enhancement, i have to solve some little bugs.

I notice your point on my roadmap.

**Comment by hitestji** [comment]
Dear @markusbegerow.

I have found a bug on the internet regarding the security of this plugin.

You should visit this link once: https://medium.com/@hoanhp/0-days-story-1-wp-pro-quiz-2115dd77a6d4

**Comment by markusbegerow** [comment]
Hey @hitestji,

thanks, please don't mix different topics.
Your security issue is already fixed and under review.

**Comment by markusbegerow** [comment]
![image](https://user-images.githubusercontent.com/44146279/229352119-059cd129-2592-4bcc-8e4e-69c372801ee6.png)

**Comment by markusbegerow** [comment]
![image](https://user-images.githubusercontent.com/44146279/229355439-2b8c09f3-a155-4457-9241-ab2bcfae1430.png)
