### ISSUE TITLE
Translation does not work

### ISSUE THREAD

**Issue by gerard-merkator** [markusbegerow/Wp-Adv-Quiz#10]
Hello!
I translated the plugin. Updated the translation. But the plugin is still in English. I reviewed the translation files on my server. They are fine  (there are original strings and my translation strings). I don't know what the problem is.

**Comment by markusbegerow** [comment]
Hey @gerard-merkator,

thank you for work. After the easter holidays I will provide some improvments,

Best regards

**Comment by markusbegerow** [comment]
Solution is comin'
