### ISSUE TITLE
Your language.po file not working on your site? ( here is the solution )

### ISSUE THREAD

**Issue by Farisalqolop** [markusbegerow/Wp-Adv-Quiz#11]
Hello,

For anyone who has issues with language.po files and all language's not working in his plugin

i put the file on the plugin languages folder
`[ wp-content\plugins\Wp-Adv-Quiz-main\languages ]`

And nothing happened

but when i put it on this general path
`[ wp-content\languages\plugins ]`

it's work perfectly!
so i think it's the solution.

**This is my first time here, sorry if I'm using this space incorrectly**
and thank you so much Mr.Mark for this great plugin.

**Comment by markusbegerow** [comment]
Thanks @Farisalqolop!
We look into it and improve this part.

**Comment by markusbegerow** [comment]
We fixed this problem.
