### ISSUE TITLE
Number of questions per category per quiz

### ISSUE THREAD

**Issue by shaheeralam1199** [markusbegerow/Wp-Adv-Quiz#13]
Hi! How can we assign number of questions per category like if i have multiple category,
1. Math
2. English
3. History

And I want to assign total 20 questions

1. Math (10 random questions out of 20)
2. English (8 random questions out of 10)
3. History (2 random questions out of 18)

How can I do this?

**Comment by markusbegerow** [comment]
Hey @shaheeralam1199,

do you want to combine different quizzes to a container?
