### ISSUE TITLE
COMO PUEDO CAMBIAR LA POSICION DE LOS RESULTADOS 

### ISSUE THREAD

**Issue by RGOMEZ2290** [markusbegerow/Wp-Adv-Quiz#15]
HOLA ME GUSTARIA SABER COMO PUEDO CAMBIAR LA POSICION DE LOS RESULTADOS PARA PONER POR ENCIMA EN LOS RESULTADO LOS CAMPOS PERSONALIZADOS

**Comment by markusbegerow** [comment]
![image](https://user-images.githubusercontent.com/44146279/229307385-a3ffe15d-f509-4087-b849-41488fbd0b6a.png)
