### ISSUE TITLE
Migrating quizzes from non-active WP-PRO-QUIZ

### ISSUE THREAD

**Issue by Andy4258** [markusbegerow/Wp-Adv-Quiz#17]
Hello, I wonder if you could help me. My original WP-PRO-QUIZ plugin stopped working due to the change to version PHP 8 on the provider´s servers. 
I have installed WP-ADV-QUIZ and I´d like to migrate my old quizzes through .xml deposit. However, as the original PRO-QUIZ plugin cannot be activated any more, I am wondering if there is any way to get the data from inside the web. Could you provide me with some advice, please?

**Comment by markusbegerow** [comment]
Hey @Andy4258,

in the end of year there will be a great update incl. an migration tool.
My team and I are working on that right now.

**Comment by greenoid** [comment]
SOLUTION:
In Wp-Pro-Quiz in file WpProQuiz_Helper_Until.php change:
$c = $format{$i};
to
$c = $format[$i];
and

};
to
$c = $format[$c];

Now you can export your quizzes as XML without an error and import it into Wp-Adv-Quiz.
At least this worked for me.

**Comment by markusbegerow** [comment]
Good point @greenoid , the curly braces are the problem
