### ISSUE TITLE
Add integration with myCred

### ISSUE THREAD

**Issue by gerard-merkator** [markusbegerow/wp-adv-quiz#18]
myCred is a points management system: https://mycred.me
Wp-Pro-Quiz had 'mycred-for-wp-pro-quiz' addon: https://gist.github.com/mycred/11c1b62ccbd063cc687dbc211d7759e9
You can do the same for 'Wp-Adv-Quiz'.

**Comment by markusbegerow** [comment]
Hey @gerard-merkator,
this very interesting. If we plan to integrate it, woul you test the new feature?

**Comment by gerard-merkator** [comment]
I would test the new feature on my site as a user. Because I'm not a programmer. I'm just a simple WordPress user. In addition, lately I have problems with electricity (((

**Comment by gerard-merkator** [comment]
I think that quiz function in LearnDash (learning management system) based on Wp-Pro-Quiz plugin. LearnDash integrated with myCred. Perhaps the following materials will be useful to you:
- myCred LearnDash (Quizzes): https://codex.mycred.me/chapter-iii/freebies/mycred-learndash/mycred-learndash-quizzes/
- myCred Learndash addon: https://mycred.me/store/mycred-learndash/
- myCred Learndash plugin for WordPress: https://wordpress.org/plugins/mycred-learndash/
- Learndash quizzes: https://www.learndash.com/support/docs/core/quizzes/

In addition, you can add: 
- Award points scored during the test ($points).
- Count all scored points together and at the same time the points of each quiz category separately.

**Comment by markusbegerow** [comment]
I take this on the roadmap!

**Comment by markusbegerow** [comment]
@gerard-merkator It's ready for 1.0.3
