### ISSUE TITLE
'Results Text' Option and Template management not Working

### ISSUE THREAD

**Issue by hitestji** [markusbegerow/Wp-Adv-Quiz#2]
Dear @markusbegerow 

Recently I got another issue.

We add "'Results Text'" option to the text that appears when the quiz is completed, but when I used it, it is not working.

I once put the text in it and saved it, but when I re-opened the quiz setting after 1 minute, I saw that the 'Results Text' option did not contain the text I entered. It was completely empty.

Apart from this, when we save the setting of a quiz in the template, it is not saved.

Please give some suggestions.

Should I use wp-pro-quiz?

I thought you made this quiz plugin new so it will work better

**Comment by markusbegerow** [comment]
Hey @hitestji,

could you provide more information and screenshots, because I couldn't detect any problems.

Which WordPress version do you use?
PHP version?
Do you have any screenshots, which you can provide?
Could export your quiz to recreate your issue?

**Comment by hitestji** [comment]
hi Dear @markusbegerow,

i use WordPress Version 5.9.
PHP Version is 7.4

yes, i can provide proper video of 'Results Text Option' Error.

https://user-images.githubusercontent.com/98321427/152090827-49e7595b-5d7d-4dc4-a3f8-4cbb610c3534.mp4

**Comment by markusbegerow** [comment]
Hey @hitestji,

I have reproduced your video with my quizzes - no error - what kind of language is that?
Could you use english as plain text and try it again?

Otherwise try to export your quiz, provide a copy and I will test it.

**Comment by hitestji** [comment]
I have found solution to my problem.

However, when I was pasting the emoji in the text, the plugin was unable to save it.

This line is for the user who uses the quiz. : If we paste emoji with text then plugin will not save it, so never paste emoji with text like i did in a video above.

Thank you.

@hitestji
