### ISSUE TITLE
(issue) Quiz Toplist

### ISSUE THREAD

**Issue by hangeul-lee** [markusbegerow/Wp-Adv-Quiz#22]
The number of questions is the same, but the score for each question is different. However, the highest score is not first in the list. how can i solve this problem?

![IMG_FDD9F04B4723-1](https://user-images.githubusercontent.com/84234322/208564129-876546ae-aafd-44ee-8420-5ba4e818b0a5.jpeg)

**Comment by markusbegerow** [comment]
Hey @hangeul-lee,

you can sort the entries by user, newest or oldest:
![image](https://user-images.githubusercontent.com/44146279/229307002-bf3947bb-f290-45b2-92d8-fde6bacd9910.png)
