### ISSUE TITLE
Cannot add quiz to wordpress

### ISSUE THREAD

**Issue by ivanli0** [markusbegerow/Wp-Adv-Quiz#23]
<img width="768" alt="Screenshot at Jan 06 00-30-26" src="https://user-images.githubusercontent.com/122064508/210905636-60e268af-e720-43ac-9b43-401a12764d79.png">
<img width="1040" alt="Screenshot at Jan 06 00-32-32" src="https://user-images.githubusercontent.com/122064508/210905783-f85f04ce-59a3-4fc5-bd00-866a8edc9d03.png">

As shown, created quizzes but cannot upload them on WordPress.

**Comment by markusbegerow** [comment]
Hey @ivanli0,

could you please provide any information?

WordPress Version?
Gutenberg on/off?
Any other configs?

At the moment there is no Gutenberg support...

**Comment by markusbegerow** [comment]
Please, use the shortcodes in Gutenberg like I do:
![image](https://user-images.githubusercontent.com/44146279/229304033-4838c86e-2566-4e65-90c9-c20ba83ab493.png)
