### ISSUE TITLE
Some signs are displayed incorrectly

### ISSUE THREAD

**Issue by gerard-merkator** [markusbegerow/Wp-Adv-Quiz#24]
In "Check -> continue" mode and when maximum number of displayed questions - X from X questions, some signs are displayed incorrectly. HTML code is shown instead of a sign.

For example: HTML code `&#8217;` instead apostrophe sign '

**Comment by markusbegerow** [comment]
Could you provide a screenshot @gerard-merkator , please?

**Comment by gerard-merkator** [comment]
![incorrectly signs 2](https://user-images.githubusercontent.com/99072684/229447659-336fb678-9aa3-4da8-a37f-5b5b64be57f7.png)
![incorrectly signs 1](https://user-images.githubusercontent.com/99072684/229447664-ec96385f-7115-4fbb-969a-7bac99d6cfdf.png)

**Comment by markusbegerow** [comment]
@gerard-merkator 
solution is comin'...

**Comment by markusbegerow** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/44146279/230393371-0588e267-580f-4cd2-91b2-5443c372cb6d.png)
