### ISSUE TITLE
No import in WP 6....

### ISSUE THREAD

**Issue by meteovigo** [markusbegerow/Wp-Adv-Quiz#25]
![Captura de Pantalla 2023-02-10 a las 12 04 05](https://user-images.githubusercontent.com/117818869/218076892-faecfad2-703d-4837-a007-f39026382195.png)
Good afternoon, I'm trying to export and import the database from the old WP_pro_QUIZ, but I get this error. Could you tell me how to do the correct migration? Thank you. Is it possible to migrate with WP 6? 

Thanks!!

**Comment by markusbegerow** [comment]
Hey @meteovigo,
try to export your files and import these files into the new one.

Best regards
Markus
