### ISSUE TITLE
Import WPQ format 

### ISSUE THREAD

**Issue by Gojak** [markusbegerow/Wp-Adv-Quiz#26]
Hi,
I would greatly appreicate if you could help me to figure out is there any way to import "wpq" format export files from WP Pro Quiz to WP-Adv-Quiz? Since the legacy plugin is broken (my domain has been updated to PHP8 and there is no going back) I can't export quizes in XML format, only in WPQ format. Can you please help?

**Comment by markusbegerow** [comment]
We will provide a proper solution in the next few days

**Comment by Gojak** [comment]
I managed to find my XML backups on my other laptop. That was close! I have imported XMLs and everything works just fine. Amazing! Thank you for this plugin.

**Comment by markusbegerow** [comment]
Hey @Gojak,
sounds great, but maybe i will create a sideproject for import and export the quizzes.
Today I will publish a new version 1.0.1. Stay tuned ;)

**Comment by greenoid** [comment]
SOLUTION:
In Wp-Pro-Quiz in file WpProQuiz_Helper_Until.php change:
$c = $format{$i};
to
$c = $format[$i];
and
$c = $format{$};
to
$c = $format[$c];

Now you can export your quizzes as XML without an error and import it into Wp-Adv-Quiz.
At least this worked for me.

**Comment by Gojak** [comment]
Thanks!
