### ISSUE TITLE
Suggestion: Add a custom title & message body to custom fields screen

### ISSUE THREAD

**Issue by Tomer-Aharoni** [markusbegerow/wp-adv-quiz#27]
Hi,
It would be nice to be able to write a custom title & message on the custom fields screen.
i.e. "Before we continue... we would like to keep in contact :)"

**Comment by markusbegerow** [comment]
Hey @Tomer-Aharoni,

this is actual possible to create a startup screen.

**Comment by Tomer-Aharoni** [comment]
Hi, I'm talking about the custom fields screen, right before the results screen.
I want to ask the user nicely to put his phone number and etc so we can reach him back.

**Comment by markusbegerow** [comment]
I will check this, but it needs time.

**Comment by markusbegerow** [comment]
Ok, I've checked your prop...

Your feature is already possible: 
![image](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/e519abbc-12dd-4173-9905-c0ebcaebf32f)

You could implement a shortcode or a form to get user information.
