### ISSUE TITLE
Suggestion: Custom coloring & rtl support

### ISSUE THREAD

**Issue by Tomer-Aharoni** [markusbegerow/Wp-Adv-Quiz#28]
Can you please add more coloring controllers?

Main background bolor
Correct/incorrect messages colors
Answers section background color
"Question X of Y" color
etc.

And about the rtl - can you please add rtl direction support to the whole quiz?
That can help a lot.
It will effect the answers direction and the default text direction.

**Comment by markusbegerow** [comment]
Hello @Tomer-Aharoni ,

more coloring controllers will comin' soon.
RTL Support: I have never done that before, do you have any sources to implement that in WP-Plugins?

**Comment by Tomer-Aharoni** [comment]
RTL support is actually pretty easy using the css properties of text-direction: rtl; and text-align: right;
The thing about it is that right now it is not declared so every theme i use responses diffrently, so you need to add those properties and add !important tag to each one of them.

**Comment by markusbegerow** [comment]
Our buddy @NohaelKa found a solution for RTL
I would like to refrence it here: https://github.com/markusbegerow/Wp-Adv-Quiz/issues/34
