### ISSUE TITLE
How to turn off exam quiz scores

### ISSUE THREAD

**Issue by leiraven** [markusbegerow/wp-adv-quiz#29]
hello!
I created a quiz and disabled the "Show category score" option. However, after finishing the quiz, the test score is still displayed on the screen.

**Comment by leiraven** [comment]
After the setup is completed, the test score will still be displayed on the screen at the end of the test.

![圖片1](https://github.com/markusbegerow/Wp-Adv-Quiz/assets/128878368/699e2ac3-8443-4edb-a44a-601c94227848)
![圖片2](https://github.com/markusbegerow/Wp-Adv-Quiz/assets/128878368/54dae12a-cf1b-436d-a529-3e237045f62f)

**Comment by leiraven** [comment]
Hello, do you have the latest adjustment information?

**Comment by markusbegerow** [comment]
I take this on the roadmap

**Comment by markusbegerow** [comment]
@leiraven : Solution is implemented and will be rolled out in the next update.
