### ISSUE TITLE
Buttons below instead checkbox

### ISSUE THREAD

**Issue by Kpk1l** [markusbegerow/Wp-Adv-Quiz#30]
Hey.
It is possible to have A, B, C ... buttons (instead checkbox/radio inputs) below the answers?
https://ibb.co/GpfyZSJ

**Comment by markusbegerow** [comment]
Hey @Kpk1l,

i will look into that nice feature.

Best regards

**Comment by markusbegerow** [comment]
One possible solution is to highlight the button A and click next.
Sounds that feasable?
