### ISSUE TITLE
Suggestion - Practice Mode / Show Answer

### ISSUE THREAD

**Issue by jchildrose** [markusbegerow/wp-adv-quiz#32]
An option to take the exam in "Practice Mode" where there would be a toggle button to show the correct answer and explanations for the current question (and toggle back to original question view when pressed again) would be a useful addition.

**Comment by markusbegerow** [comment]
Hey @jchildrose,

you could provide the answer after every question with right or wrong.

**Comment by jchildrose** [comment]
Agreed. But I was thinking from taking a practice exam from my perspective as a test taker- I don't necessarily need the validation on every question - just the ones I'm not sure about.

**Comment by markusbegerow** [comment]
![image](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/8ed19fad-f599-4304-9f06-71f13e75a800)

![image](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/77094711-cae0-420f-8652-19019df3bd08)

![image](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/ac84346a-8a93-427c-8252-be43d2d1861c)
