### ISSUE TITLE
How to export quiz?

### ISSUE THREAD

**Issue by NohaelKa** [markusbegerow/Wp-Adv-Quiz#33]
I see there is an import option, but I dont know how to format the Json file in order for it to succeed, so I thought I would export it first then make modifications, but I cant find a way to do it.

Thanks for the great plugin btw!

**Comment by NohaelKa** [comment]
I found in the quiz questions and answers a drop down for export

**Comment by markusbegerow** [comment]
Sorry @NohaelKa for my delayed repsonse.
At the moment i'm really busy.

**Comment by NohaelKa** [comment]
No issue at all!

**Comment by GerardGielen** [comment]
I use WP-Pro Quiz. What is the difference with the new one WP Adv Quiz. Is it usefull to do export/import for every quiz of is there coming a tool to do it all at once?   Until now WP-Pro Quiz is working fine but there is no update again. Do I have to change to the new version? I see that there is a difference in the lay out of the dashboard, but it seems that the rest of the system is the same???  By the way I like the plugin very much!!!
