### ISSUE TITLE
Error: "This block has encountered an error and cannot be previewed" in WP 6.3

### ISSUE THREAD

**Issue by massive-share** [markusbegerow/Wp-Adv-Quiz#35]
Hi,
I just tried to install this plugin in WP 6.3 and when I try to add the quiz into a page, I have this error:

> This block has encountered an error and cannot be previewed
<img width="458" alt="Capture d’écran 2023-08-12 à 15 08 37" src="https://github.com/markusbegerow/Wp-Adv-Quiz/assets/99491645/7dab87e2-c458-4e92-94df-436eb92ba85a">

Did I miss something?
Thank you for your help

**Comment by markusbegerow** [comment]
Hello @massive-share,

at the moment we will only support WP 6.2, but we will fix it.

Best regards
Markus

**Comment by markusbegerow** [comment]
@massive-share : Please use this shortcodes at the moment:
![image](https://github.com/markusbegerow/Wp-Adv-Quiz/assets/44146279/b3355d95-c85f-436a-a648-d19d8c5c3fc9)

We're working on a solution

**Comment by markusbegerow** [comment]
We have fixed the problem
![image](https://github.com/markusbegerow/Wp-Adv-Quiz/assets/44146279/2e3a8e4a-6f82-4403-8fa0-01572c202c1c)

The new version is comin' next week - thanks for wating

**Comment by markusbegerow** [comment]
Update is comin' today
