### ISSUE TITLE
Short code is being printed [WpAdvQuiz_toplist 2 q="true"] but unregsitered user is not asked to sign up for leaderboard

### ISSUE THREAD

**Issue by NohaelKa** [markusbegerow/wp-adv-quiz#38]
Currenlty only registered user is appearing in the leaderboard, the unregesistered user is not being asked to put his details to be in the leader board.
This short code is printed as is in the preview:
[WpAdvQuiz_toplist 2 q="true"]

**Comment by markusbegerow** [comment]
Hey @NohaelKa,
sign up is not planned. But we could make it invisible.

**Comment by NohaelKa** [comment]
A small update, in file WpAdvQuiz_View_FrontQuiz.Php in the following function:
2private function showAddToplist()
    {
        ?>
        <div class="wpAdvQuiz_addToplist" style="display: none;">2

When I removed "style="display: none", the signup box for leaderboard appeared for user that is not signed in, but when I fill it out it still doesnt do anything.

**Comment by NohaelKa** [comment]
Ok I think it is a general issue that the leaderboard is only showing 1 username even though there are several entries.  For info Im still using version 1.0.1

**Comment by markusbegerow** [comment]
So I've tested it. it works as designed...

Anonymous:

![Image](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/2e9d20a6-d2df-413e-ae15-ea78e88c9370)

Please provide more info for improvements
