### ISSUE TITLE
How to export questions from Wp-Pro-quiz

### ISSUE THREAD

**Issue by brandonc89** [markusbegerow/wp-adv-quiz#42]
Hi, I am trying to get all of my questions/quizzes from wp-pro-quiz into Wp-Adv-Quiz and ran into an issue when trying to export. I have tried exporting XML and it crashes my site with a fatal error. Does anyone have any idea how I could get migrated over to the new plug-in without having to recreate all my quizzes? Any help greatly appreciated!

**Comment by markusbegerow** [comment]
Hey @brandonc89,

could you please provide a screenshot of your error message?
Any further information is helpful...

**Comment by brandonc89** [comment]
Thank you for the reply, it turns out that my ability to export via XML was related to other incompatibilities and site issues that, once resolved, allowed me to export the file.

My problem now is that Wp-adv-quiz will not allow me to import the XML file I exported from wp-pro-quiz as the file size is too large (9Mb). Is there another way I can import the questions? I DO still have access to an old backup of my /wp-content/plugins/wp-pro-quiz/ but not sure if I can just upload that folder back into my back-end and have wp-adv-quiz recognize the data?

Any help would be greatly appreciated! Thank you!

**Comment by markusbegerow** [comment]
Hey @brandonc89,

thank you for using the tool. I appreciate that.

I still work on a little extra tool for exporting the old quizzes to import into the new plugin.
Please be patient - it is still one of my hobby projects, but it will be ready soon

all the best

**Comment by markusbegerow** [comment]
Hey @brandonc89 

a solution is comin'. I take your point on the roadmap-

**Comment by markusbegerow** [comment]
Hey @brandonc89,

I've checked your problem. I guess its your wp instance and not the plugin. Could you provide a screenshot of your error message? Otherwise please check this link for help: https://wordpress.stackexchange.com/questions/113055/import-wordpress-xml-file-larger-than-8mb
