### ISSUE TITLE
mathematics symbols show in HTML code

### ISSUE THREAD

**Issue by iahsan** [markusbegerow/wp-adv-quiz#43]
I am trying to use the plugin to setup some maths quizzes but some symbols, mainly, ÷ show up as HTML code (&#247;) on the webpage.

Any help/suggestions would be highly appreciated ...

**Comment by markusbegerow** [comment]
Hello @iahsan ,

could you give me a screenshot of your probs?

Best regards
Markus

**Comment by markusbegerow** [comment]
sorry @iahsan you didn't provide any samples to investigate
