### ISSUE TITLE
Frontend Category Resuts Displaying Incorrect CSS Code

### ISSUE THREAD

**Issue by dantedmn** [markusbegerow/wp-adv-quiz#46]
Howsit, your code for CSS isn't outputting correctly for category results. For some reason its double wrapping the " marks of the style response which is invalidating the display: none;

Here are some screenshots of the issue:
<img width="528" alt="Screenshot 2023-11-10 at 11 09 31 AM" src="https://github.com/markusbegerow/Wp-Adv-Quiz/assets/97432821/1a35714c-bde0-43b3-9159-24198ca82095">
<img width="757" alt="Screenshot 2023-11-10 at 11 09 49 AM" src="https://github.com/markusbegerow/Wp-Adv-Quiz/assets/97432821/0a1ae975-7ffd-4b55-98eb-229bef9634db">
<img width="410" alt="Screenshot 2023-11-10 at 11 09 58 AM" src="https://github.com/markusbegerow/Wp-Adv-Quiz/assets/97432821/ae681c31-c5d3-4d49-b1fb-2dc89205d07d">

I have selected to not display these results so its doing the right thing just the wrong way.

**Comment by markusbegerow** [comment]
@dantedmn thank you very much, solution is implemented
