### ISSUE TITLE
*.Json sample for importing question

### ISSUE THREAD

**Issue by Phyxian13** [markusbegerow/wp-adv-quiz#47]
I have been exploring the project but did not find any sample/format to import questions through *.json. Where can i find the sample code.

**Comment by asen0v** [comment]
Hey! I'm looking for the same, as I have around 100+ quizzes, it would be helpful if we have a sample format to import them instead of 1 by 1. Thank you!

**Comment by markusbegerow** [comment]
Hello @Phyxian13 & @asen0v ,

at the moment there is no json support.
You can use XML or native WAQ file.

Best
Markus

**Comment by markusbegerow** [comment]
Here is the sample as json
{"version":"1.0.2","export_version":1,"date":1703049876,"questions":[{"sort":1,"title":"adsas","question":"<strong>sdas<\/strong>","correct_msg":"","incorrect_msg":"","answer_type":"single","correct_same_text":false,"tip_enabled":false,"tip_msg":"","points":1,"show_points_in_box":false,"answer_points_activated":false,"category_name":"sfsed","answer_points_diff_modus_activated":false,"disable_correct":false,"matrix_sort_answer_criteria_width":20,"answer_data":[{"answer":"A","html":true,"points":1,"correct":true,"sort_string":"","sort_string_html":false},{"answer":"B","html":true,"points":1,"correct":false,"sort_string":"","sort_string_html":false}]}]}
