### ISSUE TITLE
Disabled categories showing in results page

### ISSUE THREAD

**Issue by asen0v** [markusbegerow/wp-adv-quiz#48]
Hello Markus!
Even thought showing the categories option is disabled, it is showing at end of the quiz what are the categories of the quiz.
May you have a look and how to disable it?

![showcategory](https://github.com/markusbegerow/wp-adv-quiz/assets/79513147/d8a88065-011a-4207-830a-3fd7da666478)
![finishquiz](https://github.com/markusbegerow/wp-adv-quiz/assets/79513147/cf26c864-11ce-457f-b34b-41944bbe2e45)

**Comment by markusbegerow** [comment]
Hey @asen0v 
Many thanks for your support. Many small bugs will be solved by the end of the year. We are on it

**Comment by markusbegerow** [comment]
@asen0v  Solutions is implemented and will be fixed in the next update
