### ISSUE TITLE
Calling Shortcode From PHP

### ISSUE THREAD

**Issue by dantedmn** [markusbegerow/wp-adv-quiz#50]
Hi there man, I have been trying to run your shortcode for a quiz using do_shortcode in a php function and then output the result. I dont seem to be getting it to run, have you anything thoughts on why this may be happening?

**Comment by markusbegerow** [comment]
Hey @dantedmn 

at the moment you can use our gutenberg block or shortcodes like this one: [WpAdvQuiz 1]
