### ISSUE TITLE
All users are not shown in the Statistics' history

### ISSUE THREAD

**Issue by Mamun528** [markusbegerow/wp-adv-quiz#52]
I refreshed several times but all users are not shown in the Statistics' history page. I see only one user who has participated in the quiz; though I have selected 10 for how many entries should be shown on one page, it shows only one user in the list.

I used a Custom field for user naming. It is used when starting the quiz. 

User: Anonymous  | Full name (Custom Field): Mamun Hossen | 

And then nothing is found in the list even when more users participate and submit. I refreshed several times. 

By the way, otherwise, I loved this plugin.

**Comment by markusbegerow** [comment]
Hey @Mamun528,

thank you so much for your support.
Could you provide your quiz as export or create some screenshots for me?

**Comment by markusbegerow** [comment]
no info provided
