### ISSUE TITLE
Upcoming update 1.0.3

### ISSUE THREAD

**Issue by markusbegerow** [markusbegerow/wp-adv-quiz#54]
Hello wp-adv-quiz-User,

thank you so much for your support to improve our lovely quiz-app.
At the end of the year, we will provide our next update.

Here you can see the progress of the update:

https://github.com/users/markusbegerow/projects/8

And please vote
https://github.com/markusbegerow/wp-adv-quiz/discussions/55

**Comment by markusbegerow** [comment]
We will need more time after all, as the project will be subject to a holistic safety investigation.

Thank you for your patience

**Comment by markusbegerow** [comment]
So the complete reivew is done... Update 1.0.3 is coming with the following features https://github.com/users/markusbegerow/projects/8, which are marked as done

**Comment by DzhumaID** [comment]
take a look at the problem.
https://github.com/markusbegerow/wp-adv-quiz/issues/69#issue-2132291299
