### ISSUE TITLE
Pls consider following features before release 1.0.3 big thanks sir in advance

### ISSUE THREAD

**Issue by santoshkumarpsda** [markusbegerow/wp-adv-quiz#57]
...kindly atleast implement two main features 1. importing bulk questions/quizes in  .xsl or .xlsx or .doc format.. 2.Negative Marking

**Comment by markusbegerow** [comment]
The easier one wins at the moment

**Comment by santoshkumarpsda** [comment]
[](url)
[learndash wp-quiz-import-export.zip](https://github.com/markusbegerow/wp-adv-quiz/files/13744077/learndash.wp-quiz-import-export.zip)

**Comment by johndjchan** [comment]
any progress on this pls

**Comment by markusbegerow** [comment]
2.Negative Marking is comin'

**Comment by johndjchan** [comment]
hi there, any update pls?
i see its closed as completed
but still dont see the bulk upload function?
https://github.com/markusbegerow/wp-adv-quiz/issues/70
