### ISSUE TITLE
If Possible add clear responses

### ISSUE THREAD

**Issue by santoshkumarpsda** [markusbegerow/wp-adv-quiz#59]
Enhancement
like all other exams kindly provide clear option button in case of user don't  want to mark answer after he attempted.

**Comment by markusbegerow** [comment]
![1](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/91ac07f0-5120-4e0b-b6d7-35dc1b921b9c)
![2](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/dd98549c-94c4-4347-980d-ecc0b6e58de5)
