### ISSUE TITLE
Shorting Method and Question Report

### ISSUE THREAD

**Issue by Git-Pik** [markusbegerow/wp-adv-quiz#61]
1. When I create a post on WordPress, it shows on the top. And it is good.

But in WPAvdQuiz, when I create a Quiz it shows alphabetically. And it is very annoying. When I have to add few question  to my latest Quiz, I have to search the name or check the list.

If it could possible to to show them as "Latest Quiz", it would be great. 

2. If some question has wrogn ans or the question is wrogn and students want to report the question, then don't do that.

So, You add a opton to the quiz section. When owner check the option, for specific quiz, the students get a small report icon to every questions of the quiz and they report the questions. a pop up will open and they send the message.

Also a specific tab show in Wordpress, the reported questions no and related Quiz and What is the message. We can also, check them to solve to delete the reported mark from the list.

Thank You. You are doing a great job. 💞

**Comment by markusbegerow** [comment]
Good idea, but low priority...

**Comment by Git-Pik** [comment]
Negative marking? 😉

**Comment by markusbegerow** [comment]
Please provide one idea in one post. Mixing content is not really helpful, so the low prority is for my backlog

**Comment by Git-Pik** [comment]
> Please provide one idea in one post. Mixing content is not really helpful, so the low prority is for my backlog

Yes, you are right. For now, I think Negative Marking is very important and useful features.

**Additional:** 

I found some useful links, I am not a developer, so I don't know about the authenticity. But here are the useful links: 

1. CSV export - https://github.com/fbattarra/wp-quiz-pro-exporter
2.  Individual users score at the bottom of their profile page: https://github.com/nijjwal/wp-pro-quiz-users-score
3. VIEW LIKE OFFICIAL ONLINE EXAMS: https://github.com/ddapsc/WP-PRO-QUIZ-NEW-LOOK
4.  Wp Pro Quiz CRUD Question: https://github.com/Kanyanmanoj/wp-pro-quiz-crud-question

**Comment by markusbegerow** [comment]
Negative Marking is comin'
