### ISSUE TITLE
How to generate file for import?

### ISSUE THREAD

**Issue by ashaqhussain** [markusbegerow/wp-adv-quiz#62]
I decided to try this plugin. But dont know how to generate xml file for import. :(
Is there any template or tutorial how to do that. plz

**Comment by markusbegerow** [comment]
Hey @ashaqhussain,

please create a new quiz with some questions. Now you can export the file to xml und checkout the structure ;)

**Comment by markusbegerow** [comment]
info: solution delivered - no response :(
