### ISSUE TITLE
Blank page where the shortcode inserted

### ISSUE THREAD

**Issue by zakwanoe** [markusbegerow/wp-adv-quiz#63]
Hi,
I have been using this quiz plugin for months, suddenly (I don't know when it started) the page where I installed the quiz becomes blank. If I go to the quiz preview it's also blank.

I have tried clearing the cache and previously there was a cache plugin that I have also removed.
Please help I don't know what's wrong.
Thank you

**Comment by markusbegerow** [comment]
Hey @zakwanoe,
do you have any logs for me.
Otherwise I create a new wp instance and check this for you.

**Comment by markusbegerow** [comment]
I will look into it

**Comment by markusbegerow** [comment]
I couldn't recreated your prop.

But try to unload your plugins step by step and reload them
