### ISSUE TITLE
Just wondered why not in WP repository

### ISSUE THREAD

**Issue by budley** [markusbegerow/wp-adv-quiz#64]
Hello and happy 2024.
I was just wondering why this plugin isn't in the WP repository please. I can imagine there are many great reasons, but it just makes me a little nervous to use it.
I've inherited a very old website that uses the WP Pro Quiz plugin and need to get everything up to date - looks like WP Adv Quiz would be the perfect replacement (instead of having to rebuild the quiz from scratch in another system!) so I'm interested to switch the site across to it (in reality will be building on a new WP install and trying to bring the existing data across).
I have the utmost respect for people building and sharing code the way you are - keep up the good work!!!
Thanks,
Gerald

**Comment by markusbegerow** [comment]
Hello Gerald (@budley) ,

we are currently being supported by the WordPress team and the plugin is undergoing a complete review so that we are still on the safe side. For more infos: https://de-at.wordpress.org/plugins/advanced-quiz/

Best regards
Markus
