### ISSUE TITLE
The picture in the question cannot be displayed properly

### ISSUE THREAD

**Issue by leiraven** [markusbegerow/wp-adv-quiz#66]
It is very urgent to improve the problem of missing test questions. Please help. Thank you.

Test question settings
![螢幕擷取畫面 2024-01-25 141911](https://github.com/markusbegerow/wp-adv-quiz/assets/128878368/8a8001ad-78c4-4a87-ab93-285dd1e76966)
![螢幕擷取畫面 2024-01-25 141958](https://github.com/markusbegerow/wp-adv-quiz/assets/128878368/ec3ffefe-6ada-4c15-8248-bb322f03c8c0)

The results presented in the exam paper
![螢幕擷取畫面 2024-01-25 141758](https://github.com/markusbegerow/wp-adv-quiz/assets/128878368/9fd4cf37-bac3-4af1-8e88-d492f9ebaead)

**Comment by iahsan** [comment]
I am having the exact same issue. Images display fine on the 'Edit Question' page but don't show in the actual quiz at all.

**Comment by Git-Pik** [comment]
Also, I have the same issue.

**Comment by markusbegerow** [comment]
Fix is comin'
![image](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/04e11ddd-d0de-4b9b-8473-19e1b918ce16)

**Comment by iahsan** [comment]
> Can we please ask when is the update expected?

A very polite request for a fix to the images not showing problem.

**Comment by markusbegerow** [comment]
Update is there

**Comment by iahsan** [comment]
> Update is there

thank you so much ...
