### ISSUE TITLE
Question 2nd line problem.

### ISSUE THREAD

**Issue by Git-Pik** [markusbegerow/wp-adv-quiz#68]
I enter "enter" and add text in 2nd line.  But in real quiz it shows side by side like one single line. It happens from new update. Please keep eye on it. It's a very big problem. Thank You.

**Comment by markusbegerow** [comment]
Hey @Git-Pik,

I need more information about location, screenshot and so on.

**Comment by Git-Pik** [comment]
> Hey @Git-Pik,
> 
> I need more information about location, screenshot and so on.

![Group 1](https://github.com/markusbegerow/wp-adv-quiz/assets/155253022/70229b40-e784-4591-8c0f-8739299be27d)

**Comment by markusbegerow** [comment]
Fix is comin'
![image](https://github.com/markusbegerow/wp-adv-quiz/assets/44146279/dc7ff94e-53c1-4fb8-91d6-ad0ce13468dd)

**Comment by markusbegerow** [comment]
Update is there
