### ISSUE TITLE
Is it necessary to change from Wp-Pro Quiz to WP Adv Quiz and how to do it easily?

### ISSUE THREAD

**Issue by GerardGielen** [markusbegerow/wp-adv-quiz#72]
I use WP-Pro Quiz. What is the difference with the new one WP Adv Quiz. Is it usefull to do export/import for every quiz of is there coming a tool to do it all at once? Until now WP-Pro Quiz is working fine but there ares no updates anymore. Do I have to change to the new version? I see that there is a difference in the lay out of the dashboard, but it seems that the rest of the system/working is the same??? Do I have to install all the templates again? Export/import all the quizzes.
By the way I like the plugin very much!!! Good work. Thanks.

**Comment by markusbegerow** [comment]
We're working on a migration path - still developin'

**Comment by markusbegerow** [comment]
Update is comin'... thx for your patience

**Comment by johndjchan** [comment]
hi any update?

**Comment by markusbegerow** [comment]
Short update - would you like to join a beta process?
![succes](https://github.com/user-attachments/assets/f98cf35e-0c0a-48f5-b1d1-40ae117ef305)
![error](https://github.com/user-attachments/assets/0dfe29d5-a94b-43c7-8a55-c671d4ac7ac4)

**Comment by markusbegerow** [comment]
![image](https://github.com/user-attachments/assets/f5e22450-1d57-4827-a943-682725c89fa6)

**Comment by markusbegerow** [comment]
https://github.com/markusbegerow/wp-adv-quiz/releases/tag/v1.0.4x

**Comment by GerardGielen** [comment]
It was not possible to install the plugin.
Message : Plugin could not be activated because it caused a fatal error.

**Comment by GerardGielen** [comment]
Plugin finally installed but message by migration  'Beide Plugins, WP-Pro-Quiz und WP-Adv-Quiz, müssen installiert und aktiviert sein, um die Migration durchzuführen.' I have bot plugins activated.

**Comment by GerardGielen** [comment]
Only possibility to export is through export/import xml format.  But test doesn't work good. 
I have put a Dutch translation on Wordpress but cannot import this.
