### ISSUE TITLE
IMPORT TEMPLATE 

### ISSUE THREAD

**Issue by serebi2704** [markusbegerow/wp-adv-quiz#73]
hi, since i can't find any ways to bulk import quiz to wp-adv-quiz
i try looking for another way
i am new to wordpress and python
i managed to find the json code
i really need to create an excel template for wp-adv-quiz and turn it back into json file again
Can anyone show me how to do it???

**Comment by johndjchan** [comment]
Seems the author of the plugin abandoned this plugin 
No reply at all

**Comment by serebi2704** [comment]
it's really a pity :(((

**Comment by markusbegerow** [comment]
closed - duplicated content.
