### ISSUE TITLE
Please fix the bug with displaying questions as percentages WP-Adv-Quiz

### ISSUE THREAD

**Issue by DzhumaID** [markusbegerow/wp-adv-quiz#74]
The plugin has a serious bug, the apostrophe " ' " character is output as code (& # 0 3 9 ;)
Could you please fix this?
**Update: an error with apostrophes occurs when we enable this item. (when we turn it off, all apostrophes are displayed normally)
Please fix this bug**
![327956361-82964568-6b18-4a6a-9fe3-ca9b7f9d7814](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/ad393e91-668f-44a4-b30c-3d85e0cb513f)
![327956409-b55aa2cc-bcf7-4e79-8e30-73e61d8bd3bb](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/27aeaa41-13a6-441e-aee4-99fb2997a567)
![327956769-8fd114c7-33a6-44ba-a0fb-69ae3ccb99db](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/1256b9c8-bc06-456f-ac37-9e118e02d15e)
![327958113-580392c0-5725-43b6-b6bf-895d35160a0e](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/5367d5a4-baf7-410c-bf78-97cf2a88dd14)
![scrnli_14-05-2024_13-39-15](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/6538c0ce-bb20-49ba-9ca6-fdca36667832)
![scrnli_14-05-2024_13-38-11](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/3b734fce-a9dc-480a-85b8-5c9ef21b9dd5)

**Comment by gerard-merkator** [comment]
Використовуйте інший апостроф, не прямий ( ' ), а літеру-апостроф ( ʼ )

**Comment by DzhumaID** [comment]
> gerard-merkator
Ооооо круто!
Дякую вам, так ( ʼ ) працює!

**Comment by markusbegerow** [comment]
Fixing is comin' in the next update.

**Comment by DzhumaID** [comment]
> Fixing is comin' in the next update.

Please fix another bug in future updates. When we enable the output of a certain number of questions in a test (in numbers or a certain percentage) -
The number of questions per category varies.
For example, my test is divided into 5 categories inside
1.Elementary
2. Pre-Intermediate
3.Intermediate
4. Upper-Intermediate
5. Advanced

My test has a total of 200 questions
If I enable in the settings to display 100 questions out of 200 or 50% out of 100%, then the number of questions for each subcategory will not be 20 questions, but random.
The first category has, for example, 15
The second one has 22 questions
Still others have 23 questions and so on.

Make sure that the same number of questions is displayed (this is logically correct)
![327956769-8fd114c7-33a6-44ba-a0fb-69ae3ccb99db](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/d53086e3-d57b-4fc8-9e40-a3363a5ea0a9)

Here is a link to a test where you can reproduce this error
(where each category should have 20 questions, but a random number of questions is displayed).
[https://shkoly.com.ua/test-english/] (https://shkoly.com.ua/test-english/)

**Comment by markusbegerow** [comment]
Hey @DzhumaID ,

thank you for supporting this hobby project.
Please create a new entry in github. Mixing content is not really helpful.

Best regards
MB
