### ISSUE TITLE
Problem - it is impossible to override button styles

### ISSUE THREAD

**Issue by DzhumaID** [markusbegerow/wp-adv-quiz#75]
Problem - it is impossible to override button styles.
How can these styles be overridden if they use an important property and are loaded during test loading. (they cannot be predefined).
Why do you use important?
How can I disable this block and use my own CSS theme styles?
<img width="1341" alt="Снимок экрана 2024-05-16 в 20 35 55" src="https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/f523c886-8dc2-49f9-8f0b-f228a52fef90">
![scrnli_16-05-2024_20-35-14](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/961c23b4-dc84-428d-ae5b-78b338ffe2a6)

**Comment by DzhumaID** [comment]
Buttons come in different widths (they expand depending on the length of the text). How could you think of making the button width fixed for all buttons?
And not allowing the user to clear the button width field (the default width remains 100 pixels) what nonsense. How can I disable this?

**Comment by markusbegerow** [comment]
We are not currently planning to make any changes here.
