### ISSUE TITLE
How can I change the localization of a plugin advanced-quiz? (Without installing loko translate, etc.)?

### ISSUE THREAD

**Issue by DzhumaID** [markusbegerow/wp-adv-quiz#76]
How can I change the localization of a plugin? (Without installing loko translate, etc.)?
I translated the strings using the "edit" program, and created .mo and .po files - uploaded them to a separate folder under the name of the plugin, in /languages/plugins/advanced-quiz/ - it does not work.
I tried placing the files inside the /languages/plugins/... folder (without creating a separate folder) - that doesn’t work either
![scrnli_22-05-2024_19-48-42](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/118c0363-a875-450e-a016-37d9629e063a)
![scrnli_22-05-2024_19-48-35](https://github.com/markusbegerow/wp-adv-quiz/assets/116857082/06370fc2-08ac-41f4-a417-2f35f5d5b973)

**Comment by markusbegerow** [comment]
Could you provide your files, so we can check your case?

**Comment by DzhumaID** [comment]
> Could you provide your files, so we can check your case?

Yes. The files are located here
.....www/wp-content/languages/plugins

[archive (1).zip](https://github.com/user-attachments/files/15521488/archive.1.zip)
I did the Ukrainian translation manually, but in addition to the Ukrainian, there were also files with Russian translation in this folder - most likely they were generated by WordPress itself (they didn’t work either)

**Comment by seb81** [comment]
Hi. Same problem. All because of wrong names of translation files.
Automatically downloaded with names beginning with:
`advanced-quiz-`
But everything starts working if you rename that part to:
`wp-adv-quiz-`

For example:
```
wp-adv-quiz-uk.l10n.php
wp-adv-quiz-uk.mo
wp-adv-quiz-uk.po
```

**Comment by markusbegerow** [comment]
We will fix it....

**Comment by markusbegerow** [comment]
Bugfix is coming in the next release...
