### ISSUE TITLE
installed wp adv quiz but cannot see any of the wpproquiz original quizzes

### ISSUE THREAD

**Issue by johndjchan** [markusbegerow/wp-adv-quiz#78]
installed wp adv quiz but cannot see any of the wpproquiz original quizzes

how to have thsoe wpproquiz one still show? thx

**Comment by johndjchan** [comment]
Hi anyone help ?

**Comment by gerard-merkator** [comment]
Export quiz from Wp-Pro-Quiz to a file in XML format. Then import this quiz from XML file into Wp-Adv-Quiz.

**Comment by johndjchan** [comment]
Thanks
But I have like over 3000 quizzes 
Need some seamless migration method

**Comment by gerard-merkator** [comment]
The owner of the plugin said he was working on a mass migration method

**Comment by johndjchan** [comment]
good thanks gerard
but it seems no update for long time already

**Comment by markusbegerow** [comment]
First tests look good. I think we can deliver an unstable version for testing in the next few weeks...

**Comment by markusbegerow** [comment]
Short update - would you like to join a beta process?
![succes](https://github.com/user-attachments/assets/f98cf35e-0c0a-48f5-b1d1-40ae117ef305)
![error](https://github.com/user-attachments/assets/0dfe29d5-a94b-43c7-8a55-c671d4ac7ac4)

**Comment by johndjchan** [comment]
Yes pls !

**Comment by markusbegerow** [comment]
Beta version coming next weekend...

**Comment by markusbegerow** [comment]
![image](https://github.com/user-attachments/assets/c5bf5752-46a9-4b27-882f-849a64de3fbe)

**Comment by johndjchan** [comment]
Hi waited one month still no update

**Comment by markusbegerow** [comment]
https://github.com/markusbegerow/wp-adv-quiz/releases/tag/v1.0.4x
