### ISSUE TITLE
Add Translations

### ISSUE THREAD

**Issue by Vinnpinn** [markusbegerow/Wp-Adv-Quiz#9]
Hey, thank you for updating the old wp-pro-quiz plugin.
Is it possible for you to upload the old translations onto translate.wordpress.org?
I've tested the german translations locally and they seem to be mostly completed with only a few missing. 
Since I'm not an editor for the plugins translations I can't upload the translations myself, according to [this Thread](https://make.wordpress.org/polyglots/2016/06/23/importing-mopo-files/) it should be possible to just import the existing files.

I've attached the language files.

[languages.zip](https://github.com/markusbegerow/Wp-Adv-Quiz/files/8342761/languages.zip)

**Comment by markusbegerow** [comment]
Solution is comin'
